### ISSUE TITLE
FIND IT UGM 2019

### ISSUE THREAD

**Issue by wisn** [comtran/activity#1]
| field | content |
|-------|-----------|
| URL | http://findit.ft.ugm.ac.id/competitive-programming/ |
| Registration Date | Dec 26th, 2018 - Mar 15th, 2019 |
| Warming up | Mar 17th, 2019 |
| Qualification | Mar 24, 2019 |
| Finalist announcement | Apr 1st, 2019 |
| Final | Apr 27th - 28th, 2019 |
| Participants | @comtran/salesman-nerd |

If you are participating on this competition, please comment here.

Include your team name and members, plus advisor.

**Comment by adityaemaulana** [comment]
Team: IfGaHarusBisaNgoding
Aditya Eka Maulana
Nuurshadieq
Rizki Achmad Riyanto

**Comment by ehardi19** [comment]
### Participants

Here is the known participants. Please add yourself if you are participating as well.

| Team        | Member 1 | Member 2 | Member 3 | Solved | Problems |
|--------------|---------------|---------------|---------------|-----------|--------------|
| SubscriberVayuHalilintar | Eko Hardiyanto (@ehardi19) | Ganesha Danu Enastika (@BlinfoldKing) | Novita | 1 out of 6 | String Biner |
| IfGaHarusBisaNgoding | Aditya Eka Maulana (@adityaemaulana) | Nuurshadieq (@catlaughing) | Rizki Achmad Riyanto (@rizkiar00) |
| Tuman | Muhammad Abdurrahman Al-Fatih (@MAAF72) | Anas Rasyid (@anasrasyid) | Wikan Kuncara Jati | 1 ot of 6 | Merubah PIN |

**Comment by wisn** [comment]
@ehardi19 is this completed?
